### DISCUSSION TITLE
Smooth dimming strategy

### DISCUSSION THREAD

**Discussion by pimw1** [delfick/photons#121] [Q&A] [answered]
Hi, I would like to dim by Lifx bulbs smoothly by adopting the approach of Philips Hue. I'm using Hue internal wall modules, connected to physical momentary switches (https://www.jungstore.nl/531-41-u-multipulsdrukker-met-2x2-maakcontacten-en.html).

I wanna achieve a butterly smooth dimming experience, similar to the analog world.

Philips Hue tackled this with the following stragegy:
1 - start dimming down by long-pressing (holding down) the dim-down button: brightness percentage of 0, transition of 6 seconds.  This signal is send to the light bulb, and the light bulb start applying the dim-down on its own.
2 - the bulb continues to dim down, until the button is released. This triggers the long-press-release event. This event sends a signal to the light bulb to increase the brightness with a percetage of 0, transition of 0 zero seconds. Thereby, stopping the light bulb from dimming down any further.

So basicly, what is happening: the bulb start dimming down on its own, unitl the stop signal is received. This results is visualy very appealing dimming, and very little network traffic.

I'd like to achieve the same with my Lifx bulbs. Step 1 is easy to do, but how can i do step 2? I am unable to give the light bulb the stop signal.

Regards,

Pim

**Comment by delfick** [comment, marked as answer]
Hello,

The LIFX binary protocol doesn't have a specific Stop command as such. But sending a SetWaveformOptional message will replace whatever hsbk transition is currently happening. So you could send a [SetWaveformOptional](https://lan.developer.lifx.com/docs/changing-a-device#setwaveformoptional---packet-119) with brightness to 0 and a period of 6 seconds and then to stop it you send a SetWaveformOptional with period 0 and changing none of the hsbk fields.

I assume you'd do this programmatically, but the cli equivalent is

```
lifx lan:attr d073d5001337 SetWaveformOptional -- '{"brightness": 0, "period": 6}'
lifx lan:attr d073d5001337 SetWaveformOptional -- '{"period": 0}'
```

You might be tempted to instead use [SetLightPower](https://lan.developer.lifx.com/docs/changing-a-device#setlightpower---packet-117) with a duration, however the protocol doesn't expose a message for stopping a power transition. and you can't set a partial power level.

One way you'd find complexity is I imagine you'd want that 6 seconds to be different depending on how bright the device is when you start this process?

**Comment by pimw1** [comment]
Thank you, i got it working in Home Assistant.

In configuration.yaml, i've put the rest command, including 3 variables.
-serial_variable
-brightness_variable
-transition_variable

```
rest_command:  
  lifx_brightness:
    url: 'http://192.168.178.2:6100/v1/lifx/command'
    method: "put"
    payload: |
      {
        "command": "set",
        "args": {
            "matcher": {
                "serial": [{{serial_variable}}]
            },
            "pkt_type": "SetWaveformOptional",
            "pkt_args": {
                {{brightness_variable}}
                {{transition_variable}}
            }
        }
      }
```

In the automation/script, i can refer to this as follows:
Start dimming down for 3 lights:

```
sequence:
  - service: rest_command.lifx_brightness
    data:
      serial_variable: "\"d073d1234567\",\"d073d1234568\",\"d073d1234569\""
      brightness_variable: "\"brightness\": 0.01"
      transition_variable: ",\"period\": 20"
mode: single
```

Stop dimming down for the same 3 lights:

```
sequence:
  - service: rest_command.lifx_brightness
    data:
      serial_variable: "\"d073d1234567\",\"d073d1234568\",\"d073d1234569\""
      brightness_variable: ""
      transition_variable: "\"period\": 0"
mode: single
```

> One way you'd find complexity is I imagine you'd want that 6 seconds to be different depending on how bright the device is when you start this process?

I think this is actually a bonus feature:
- when the light bulb was very bright, the dimming steps will be courser
- when the light bulb was already dimmed down quite a bit, the dimming steps will be more granualar, giving you more control

I'll implement this in an automation tomorrow and check how it works in practice. I'll let you know.

**Reply by delfick** [reply]
nice!

**Comment by pimw1** [comment]
I've implemented it in my automation. It is very, very smooth! It is even better than i imagined.
And it works beeatifully with the Philips Hue lights in my living room (for which i am functionally applying the same trick by using the Deconz integration).

> I think this is actually a bonus feature:
> 
> when the light bulb was very bright, the dimming steps will be courser
> when the light bulb was already dimmed down quite a bit, the dimming steps will be more granualar, giving you more control

In practice, this works exactly as i hoped for. If someone would like to make the transition time shorter when the light bulb was already dimmed down, one could use the transition_variable and multiply it by [initial brightness value / 255].

See below my automation, in which both Philips Hue and Lifx lights are dimmed up and dimmed down.

```
alias: alias of the automation
description: ""
trigger:
  - device_id: 5421144978f28dd04b59bb87a23843ad
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: button_2
    id: dimmer
  - device_id: 5421144978f28dd04b59bb87a23843ad
    domain: deconz
    platform: device
    type: remote_button_long_release
    subtype: button_2
    id: dimmer stop
  - device_id: 5421144978f28dd04b59bb87a23843ad
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: button_1
    id: brighter
  - device_id: 5421144978f28dd04b59bb87a23843ad
    domain: deconz
    platform: device
    type: remote_button_long_release
    subtype: button_1
    id: brighter stop
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: dimmer
          - condition: state
            entity_id: input_boolean.living_room_dimstatus
            state: "off"
        sequence:
          - parallel:
              - service: deconz.configure
                data:
                  entity: light.living_room_deconz
                  field: /action
                  data:
                    bri: 1
                    transitiontime: 50
              - service: rest_command.lifx_brightness
                data:
                  serial_variable: "\"d073d54220a3\",\"d073d5584eeb\",\"d073d55829ee\""
                  brightness_variable: "\"brightness\": 0.01"
                  transition_variable: ",\"period\": 5"
              - service: input_boolean.turn_on
                data: {}
                target:
                  entity_id: input_boolean.living_room_dimstatus
      - conditions:
          - condition: trigger
            id: dimmer stop
        sequence:
          - parallel:
              - service: deconz.configure
                data:
                  entity: light.living_room_deconz
                  field: /action
                  data:
                    bri_inc: 0
              - service: rest_command.lifx_brightness
                data:
                  serial_variable: "\"d073d54220a3\",\"d073d5584eeb\",\"d073d55829ee\""
                  brightness_variable: ""
                  transition_variable: "\"period\": 0"
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: input_boolean.living_room_dimstatus
      - conditions:
          - condition: trigger
            id: brighter
          - condition: state
            entity_id: input_boolean.living_room_dimstatus
            state: "off"
        sequence:
          - parallel:
              - service: deconz.configure
                data:
                  entity: light.living_room_deconz
                  field: /action
                  data:
                    bri: 254
                    transitiontime: 50
              - service: rest_command.lifx_brightness
                data:
                  serial_variable: "\"d073d54220a3\",\"d073d5584eeb\",\"d073d55829ee\""
                  brightness_variable: "\"brightness\": 1"
                  transition_variable: ",\"period\": 5"
              - service: input_boolean.turn_on
                data: {}
                target:
                  entity_id: input_boolean.living_room_dimstatus
      - conditions:
          - condition: trigger
            id: brighter stop
        sequence:
          - parallel:
              - service: deconz.configure
                data:
                  entity: light.living_room_deconz
                  field: /action
                  data:
                    bri_inc: 0
              - service: rest_command.lifx_brightness
                data:
                  serial_variable: "\"d073d54220a3\",\"d073d5584eeb\",\"d073d55829ee\""
                  brightness_variable: ""
                  transition_variable: "\"period\": 0"
              - service: input_boolean.turn_off
                data: {}
                target:
                  entity_id: input_boolean.living_room_dimstatus
    default: []
mode: queued
max: 10
```

Thanks again for your help! It is awesome.

PS: perhaps this methodology could be implemented as new Lifx services in Home Assistant too in the future (lifx.start_dimming , lifx.stop_dimming). I wouldn't know how, but perhaps someone would like to pick up on that.
