### ISSUE TITLE
Is it possible to avoid network_mode: host (docker)

### ISSUE THREAD

**Issue by TonyBrobston** [delfick/photons#21]
First off, thank you for putting this repo together. This seems like a really viable solution to get away from using LIFX Cloud.

I'm trying to do two things:
1. Move away from using cloud services.
2. Move away from `network_mode: host` in docker.

It seems as though `network_mode: host` should be unnecessary. When I google around for a solution `network_mode: host` seems to be the accepted answer and the rest is dismissed. Do you happen to know why this is needed?

---

I hope to have a docker-compose similar to below. Initially I will just set up a switch using a rest call in Home Assistant to turn my LIFX bulbs on/off. The equivalent of:
```
curl -XPUT http://photons:6100/v1/lifx/command -H Content-Type:application/json -d '{"command": "transform", "args": {"transform": {"power": "on"}}}'
```

Currently the call from the `home-assistant` container to the `photons` container works fine. The logs show:
```
photons_1         | 2020-09-17 11:42:55,263 INFO    tornado.access  200 PUT /v1/lifx/command (192.168.16.6) 6.46ms
```

However, the bulb's state does not change. I think this because some sort of communication needs made to the bulbs from inside the `photons` container; I'm not sure what this communication is, but that communication not being made seems to be the issue.

```
version: '3.8'

services:
  home-assistant:
    image: homeassistant/home-assistant
    restart: unless-stopped
    ports:
    - 8123:8123
    volumes:
    - ~/home-assistant:/config

  photons:
    image: delfick/lifx-photons-interactor
    restart: unless-stopped
    environment:
    - TZ=America/Chicago
    volumes:
    - ~/photons/configdir:/project/config
```

It also may be worth mentioning that I manually set my discovery settings:

```
interactor:
  host: photons
  port: 6100
  discovery_options:
    hardcoded_discovery:
      [redacted]: "[redacted]"
      [redacted]: "[redacted]"
```

**Comment by TonyBrobston** [comment]
I think I may have just realized the issue. It seems like the LIFX bulbs are not accessible from these containers because of how docker networks work. I'm now wondering if I can do some equivalent of port mapping with the IP's of my LIFX bulbs or something 🤷 .

**Comment by TonyBrobston** [comment]
I'm now thinking maybe the issue is related to photons discovering the LIFX bulbs.

**Comment by Djelibeybi** [comment]
You may want to try hardcoding the discovery of your bulbs: https://photons.delfick.com/configuration/discovery_options.html

However, I'm not sure why you're using both Home Assistant and Photons, as Home Assistant has full support for LIFX built-in: https://www.home-assistant.io/integrations/lifx/ which doesn't use the LIFX Cloud either.

**Comment by TonyBrobston** [comment]
@Djelibeybi I didn't realize that Home Assistant wasn't using the cloud. I've also tried hardcoding the discovery of the bulbs. Seems to me like that should have worked.

**Comment by Djelibeybi** [comment]
Docker's networking is ... interesting. Photons (and the LIFX app) use a UDP broadcast to discover bulbs and this is not something that Docker supports across its standard NAT network. If you don't want to share the same IP as your host via ``--network=host`, you can also use `macvlan` networking to give the container a real IP address on your network.

**Comment by TonyBrobston** [comment]
@Djelibeybi I was able to use the Advanced Configuration here: https://www.home-assistant.io/integrations/lifx/#advanced-configuration

It was able to discover one bulb, but not the other 🤷 .

```
lifx:
  light:
    - server: home-assistant
      port: 56700
      broadcast: [my fixed ip address for one bulb]
    - server: home-assistant
      port: 56700
      broadcast: [my fixed ip address for the other bulb]
```
